/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.ManagerWorkArea;

import Business.Business;
import Business.UserAccount;
import Business.UserAccountDirectory;
import Customer.Customer;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cylai
 */
public class CustomerManagementJPanel extends javax.swing.JPanel {
    private Business business;
    private UserAccount useraccount;
    DefaultTableModel tableModel;
    
    
    /**
     * Creates new form CustomerManagementJPanel
     */
    public CustomerManagementJPanel(Business business, UserAccount useraccount) {
        initComponents();
        
        this.business = business;
        this.useraccount = useraccount;
        
                
                
       populate();         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldAge = new javax.swing.JTextField();
        fieldusername1 = new javax.swing.JTextField();
        fieldPassword1 = new javax.swing.JTextField();
        fieldname1 = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(fieldAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 80, -1));
        add(fieldusername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 80, -1));
        add(fieldPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 80, -1));

        fieldname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldname1ActionPerformed(evt);
            }
        });
        add(fieldname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 80, -1));

        addBtn.setText("ADD");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, -1, -1));

        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Username", "Password"
            }
        ));
        jScrollPane1.setViewportView(customerTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 240, 200));
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        UserAccountDirectory us = this.business.getUseraccountDirectory();
        
        if(us.accountExists(fieldusername1.getText(), fieldPassword1.getText(), "customer")){
            JOptionPane.showMessageDialog(null, "Sorry credentials are taken");
        }
        else{
            UserAccount user = this.business.getUseraccountDirectory().createUserAccount(fieldusername1.getText(), fieldPassword1.getText(), "customer");
            this.business.getDeliveryAgentDirectory().createAgent(user.getAccountId(), fieldname1.getText(), fieldAge.getText());        
            populate();        
         }
        
    }//GEN-LAST:event_addBtnActionPerformed

    private void fieldname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldname1ActionPerformed

    
    public void populate(){
        
        tableModel.setRowCount(0);
        for(Customer c: this.business.getCustomerDirectory().getCustomerlist()){
            UserAccount u = this.business.getUseraccountDirectory().findById(c.getPersonID());
            
            Object[] row = new Object[4];
            
            row[0] = c.getPersonID();
            row[1] = c.getName();
            row[2] = u.getUsername();
            row[3] = u.getPassword();
            
            
            tableModel.addRow(row);
        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTable customerTable;
    private javax.swing.JTextField fieldAge;
    private javax.swing.JTextField fieldPassword1;
    private javax.swing.JTextField fieldname1;
    private javax.swing.JTextField fieldusername1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
